version : '3'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
        
  accountManager:
    image: accountmanagersba
    build: accountmanager/
    restart: always
    network_mode: host
    container_name: accountmanagersbaCon
    ports:
        - 8081:8081
    depends_on:
      - mysql
      - eurekaServer
      - rabbitmq
    healthcheck:
        test: "exit 0"
      
  muzixManager:
    image: muzixmanagerservicesba
    build: muzixmanager/
    restart: always
    network_mode: host
    container_name: muzixmanagersbaCon
    ports:
        - 8082:8082
    depends_on:
      - mongo
      - eurekaServer
      - rabbitmq
    healthcheck:
        test: "exit 0"

  muzixRecommendedService:
    image: muzixrecommendedservicesba
    build: muzixrecommendersystem/
    restart: always
    network_mode: host
    container_name: muzixrecommendedsbaCon
    ports:
        - 8085:8085
    depends_on:
      - eurekaServer
      - rabbitmq

  eurekaServer:
    image: eurekaserversba
    build: eurekaserverdemo/
    restart: always
    network_mode: host
    container_name: eurekaServerCon
    ports:
        - 9003:9003 
    healthcheck:
        test: "exit 0"

  orchestrationServer:
    image: orchestrationservicesba
    build: orchestrationservice/
    restart: always
    network_mode: host
    container_name: orchestrationServerCon
    depends_on:
      - eurekaServer
    ports:
        - 8888:8888 
    healthcheck:
        test: "exit 0"

  zuulService:
    image: zullservicesba
    build: zuulservice/
    restart: always
    network_mode: host
    container_name: zuulServerCon
    ports:
        - 8083:8083 
    healthcheck:
        test: "exit 0"       

  mysql:
    image: mysql:5.5
    ports:
        - 3306:3306
    container_name: mysql_container
    network_mode: host
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: UserDb
        MYSQL_USER: approot
        MYSQL_PASSWORD: root123


  angular:
    image: muzixuisba
    build: MuzixUI/
    network_mode: host
    container_name: muzixUiCon
    ports:
        - 8080:8080
    healthcheck:
        test: "exit 0"

  mongo:
    image: mongo:3.2-jessie
    ports:
        - 27017:27017
    container_name: mongo
    network_mode: host
    
    



