FROM java:8-jre
WORKDIR usr/src
ADD ./target/muzixrecommendersystem-0.0.1-SNAPSHOT.jar /usr/src/muzixrecommendersystem-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "muzixrecommendersystem-0.0.1-SNAPSHOT.jar"]
